name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Selection, Insertion, Merge, Quick
      id: selection-insertion-merge-quick
      uses: education/autograding-command-grader@v1
      with:
        test-name: Selection, Insertion, Merge, Quick
        setup-command: ''
        command: gradle clean test
        timeout: 10
        max-score: 80
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        SELECTION-INSERTION-MERGE-QUICK_RESULTS: "${{steps.selection-insertion-merge-quick.outputs.result}}"
      with:
        runners: selection-insertion-merge-quick
